# Generated by Django 4.2.1 on 2023-07-31 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product_is_active_alter_product_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
