# Generated by Django 4.2.1 on 2023-08-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_categories_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
