# Generated by Django 4.2.1 on 2023-08-06 12:08

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMField(default='Awaiting payment', max_length=1),
        ),
    ]
