# Generated by Django 4.2.1 on 2023-08-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_update',
            new_name='create_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_intent_id',
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.category'),
        ),
    ]
